//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_R_M.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class EstadodeCuenta
    {
        public int Id_Empresa { get; set; }
        [DisplayName("Credito Disponible")]
        //[RegularExpression(@"^-?\d*\.?\d{0,2}$", ErrorMessage ="Solo dos dijitos despues del punto")]
        [Range(-999999999999.99, 999999999999.99, ErrorMessage = "Debe ser mayor o igual a 0 y menor a 999999999999.99")]
        public decimal Credito_Disponible { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
