//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_R_M.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicidad
    {
        public int Id_Publicidad { get; set; }
        public Nullable<int> Medio { get; set; }
        public int Id_empresa { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Caducidad { get; set; }
        public Nullable<double> Costo { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual MedioPublicitario MedioPublicitario { get; set; }
    }
}
