
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace C_R_M.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Recordatorio
{

    public int Id_Recordatorio { get; set; }

    public string Tipo { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Fecha { get; set; }
        [Range(0, 23, ErrorMessage = "Ingrese una hora valida")]
        public Nullable<int> Hora { get; set; }

        [Range(0, 59, ErrorMessage = "Ingrese minutos validos")]
        public Nullable<int> Minutos { get; set; }

        public string Abreviatura { get; set; }

        public string Detalle { get; set; }

        public Nullable<int> Id_empresa { get; set; }
        [DataType(DataType.Text)]
        public string Mensaje { get; set; }



        public virtual Empresa Empresa { get; set; }

}

}
