//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_R_M.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ReportCuentas
    {
        public System.DateTime Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Primer_Pago { get; set; }
        public System.DateTime Renovacion { get; set; }
        public double Precio { get; set; }
        public Nullable<double> Monto_Pendiente { get; set; }
        public double Monto_Abono { get; set; }
        public System.DateTime Fecha_Pago { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Cedula { get; set; }
        public string Descripcion { get; set; }
        public string Producto_Adquirido { get; set; }
        public int Id_Servicio_Empresa { get; set; }
    }
}
